### ISSUE TITLE
Usage of blockexplorer.getTx

### ISSUE THREAD

**Issue by Thinkdiff** [blockchain/api-v1-client-node#34]
Could you show me an example of how to use "blockexplorer.getTx(txId, options)"

my question is about option object and txid

**Comment by jtormey** [comment]
Example:

```js
var myTxHash = '9baf942d3b9e6e4c9f952f4ed9c511d973773f994393c39d5b052c80e7e17f60'
blockexplorer.getTx(myTxHash).then(function (data) { /* do something */ })
```

`txId` is just the transaction hash for the tx you want to look up.

`options` is an (optional) object that can contain an `apiCode`, only useful if you need to increase your request limit (not necessary unless you're making a ton of requests).

**Comment by Thinkdiff** [comment]
Thanks a lot.
and how can I  know a transaction has confirmed or not? Or find total of confirmations of and 

transaction. I used your code and get these:
`{
  "ver": 1,
  "inputs": [
    {
      "sequence": 4294967295,
      "prev_out": {
        "spent": true,
        "tx_index": 249171171,
        "type": 0,
        "addr": "1spCZiP81bLQgER411w6CjMKNnTHz8NLb",
        "value": 95801266,
        "n": 1,
        "script": "76a914099c32b9cb79e751ece5a2d630fc4556acaff51288ac"
      },
      "script": "483045022100faf13b8be57a0f08819c157e34eda6b1b76801812a08cbdbbe12ed1c85672c2a022003bb39de05a40837e51971bd597627d5e4c3e322aab468baf2ed8636a8aac854012103b22a8ced7dcd91aeb74eeaf7556ff0aeb5e771537002218725bfdb06a745e39c"
    }
  ],
  "block_height": 468218,
  "relayed_by": "5.230.148.24",
  "out": [
    {
      "spent": false,
      "tx_index": 254873331,
      "type": 0,
      "addr": "1CyJc1aCZ47voPV1qcXj2t41DbNwTsSgob",
      "value": 95078248,
      "n": 0,
      "script": "76a914834f5f4b47134481d3eae768040477f27e9b987d88ac"
    },
    {
      "spent": false,
      "tx_index": 254873331,
      "type": 0,
      "addr": "1BDXhNjjrroKgU8RdXMbAYBPT8uJ51Q9YX",
      "value": 657473,
      "n": 1,
      "script": "76a914700fdf8a80bc030e67a7424aaaef806e46db287188ac"
    }
  ],
  "lock_time": 0,
  "size": 226,
  "double_spend": false,
  "time": 1495798005,
  "tx_index": 254873331,
  "vin_sz": 1,
  "hash": "67042bddaee44679180cf1a38e71686874e8509c25307d7677db673e93e5e5b6",
  "vout_sz": 2
}
`

**Comment by jtormey** [comment]
The confirmations aren't included in the transaction object returned from the server, but it's still possible to find that info with what we have.

If a transaction is confirmed, the response you receive from `getTx` will have a `block_height` property, which tells us the block that the transaction was included in. So, here's how we would find if a transaction is confirmed:

```js
blockexplorer.getTx(myTxHash).then((myTx) => {
  let isConfirmed = myTx.block_height != undefined
  // do something
})
```

To find the exact number of confirmations, we'll have to do something a bit more clever. We know the block height the transaction was confirmed at, and we can get the current block height with this API library, so with some simple subtraction we can get the number of confirmations:

```js

blockexplorer.getTx(myTxHash).then((myTx) => {
  if (myTx.block_height != undefined) {
    blockexplorer.getLatestBlock().then((latestBlock) => {
      let confirmations = latestBlock.height - myTx.block_height + 1
      // do something
    })
  }
})
```

I'm adding 1 to `confirmations` above because the block the transaction was included in counts as a confirmation. Hope that helps! Please close Github issues when your problem is resolved.
